#!/usr/bin/env python3
"""
Auto-generate bilingual README files from each extension's manifest.json + DESCRIPTION files.

Generates:
  - README.md        (English)
  - README.zh-TW.md  (Traditional Chinese)

Rules:
- Extension = any subdirectory in repo root that contains manifest.json
- DESCRIPTION.en.md provides English content; DESCRIPTION.md provides Chinese content
- Falls back to manifest["description"] if no description file exists
- __MSG_*__ manifest names are resolved via _locales/ directory

Add a new extension? Just create its folder with manifest.json.
The next push to main will auto-detect it and update README + Releases.
"""

import json
import os
import sys

REPO = "stantheman0128/stan-chrome-extensions"
BASE_DOWNLOAD_URL = f"https://github.com/{REPO}/releases/latest/download"

BADGE_COLORS = ["blue", "red", "green", "orange", "9B59B6"]

EXCLUDED = {".github", "node_modules", ".git"}

LANG_TOGGLE = "\U0001F310 [English](README.md) | [\u7E41\u9AD4\u4E2D\u6587](README.zh-TW.md)"

LABELS = {
    "en": {
        "title": "Stan Chrome Extensions",
        "subtitle": "A lightweight collection of Chrome extensions built on Manifest V3.",
        "auto_note": (
            "> **This README is auto-generated by GitHub Actions.**\n"
            "> To modify an extension's description, edit the `DESCRIPTION.en.md` file in its folder."
        ),
        "quick_download": "Quick Download",
        "table_ext": "Extension",
        "table_download": "Download",
        "ext_list": "Extensions",
        "folder": "Folder:",
        "version": "Version",
        "download_btn": "Download",
        "badge_label": "Download",
        "install": "Installation",
        "install_steps": [
            "Click the button above to download the `.zip` file and extract it",
            "Open Chrome and go to `chrome://extensions`",
            "Enable **Developer mode** in the top-right corner",
            "Click **Load unpacked** and select the extracted `{dir}` folder",
        ],
        "project_structure": "Project Structure",
        "add_new": "Adding a New Extension",
        "add_new_desc": (
            "Create a new subdirectory in the repo root with a `manifest.json`.\n"
            "The next push to main will auto-package it, update the Release, and regenerate this README."
        ),
        "license": "License",
    },
    "zh_TW": {
        "title": "Stan Chrome Extensions",
        "subtitle": "\u57FA\u65BC Manifest V3 \u6253\u9020\u7684\u8F15\u91CF\u7D1A Chrome \u64F4\u5145\u529F\u80FD\u5408\u96C6\u3002",
        "auto_note": (
            "> **README \u7531 GitHub Actions \u81EA\u52D5\u751F\u6210\u3002**\n"
            "> \u6B32\u4FEE\u6539\u64F4\u5145\u529F\u80FD\u7684\u8AAA\u660E\uFF0C\u8ACB\u7DE8\u8F2F\u5C0D\u61C9\u8CC7\u6599\u593E\u5167\u7684 `DESCRIPTION.md`\u3002"
        ),
        "quick_download": "\u5FEB\u901F\u4E0B\u8F09",
        "table_ext": "\u64F4\u5145\u529F\u80FD",
        "table_download": "\u4E0B\u8F09",
        "ext_list": "\u64F4\u5145\u529F\u80FD\u5217\u8868",
        "folder": "\u8CC7\u6599\u593E\uFF1A",
        "version": "\u7248\u672C",
        "download_btn": "\u4E00\u9375\u4E0B\u8F09",
        "badge_label": "\u4E0B\u8F09",
        "install": "\u5B89\u88DD\u65B9\u5F0F",
        "install_steps": [
            "\u9EDE\u4E0A\u65B9\u6309\u9215\u4E0B\u8F09 `.zip` \u4E26\u89E3\u58D3\u7E2E",
            "\u958B\u555F Chrome\uFF0C\u524D\u5F80 `chrome://extensions`",
            "\u555F\u7528\u53F3\u4E0A\u89D2\u7684**\u958B\u767C\u4EBA\u54E1\u6A21\u5F0F**",
            "\u9EDE\u64CA**\u8F09\u5165\u672A\u5C01\u88DD\u9805\u76EE**\uFF0C\u9078\u64C7\u89E3\u58D3\u7E2E\u5F8C\u7684 `{dir}` \u8CC7\u6599\u593E",
        ],
        "project_structure": "\u5C08\u6848\u7D50\u69CB",
        "add_new": "\u65B0\u589E\u64F4\u5145\u529F\u80FD",
        "add_new_desc": (
            "\u5728 repo \u6839\u76EE\u9304\u5EFA\u7ACB\u65B0\u5B50\u76EE\u9304\u4E26\u653E\u5165 `manifest.json`\uFF0C\n"
            "\u4E0B\u6B21\u63A8\u9001\u5230 main \u6642 GitHub Actions \u5C07\u81EA\u52D5\u6253\u5305\u3001\u66F4\u65B0 Release \u4E26\u91CD\u65B0\u751F\u6210\u6B64 README\u3002"
        ),
        "license": "\u6388\u6B0A\u689D\u6B3E",
    },
}


def find_extensions(root="."):
    extensions = []
    for name in sorted(os.listdir(root)):
        if name in EXCLUDED or name.startswith("."):
            continue
        path = os.path.join(root, name)
        if not os.path.isdir(path):
            continue
        manifest_path = os.path.join(path, "manifest.json")
        if not os.path.exists(manifest_path):
            continue
        with open(manifest_path, encoding="utf-8") as f:
            manifest = json.load(f)
        extensions.append({"dir": name, "manifest": manifest})
    return extensions


def resolve_name(manifest, ext_dir, lang="en"):
    """Resolve extension name, handling __MSG_*__ i18n format."""
    name = manifest.get("name", ext_dir)
    if name.startswith("__MSG_") and name.endswith("__"):
        key = name[6:-2]
        locale_dirs = ["zh_TW", "en"] if lang == "zh_TW" else ["en"]
        for locale_dir in locale_dirs:
            messages_path = os.path.join(ext_dir, "_locales", locale_dir, "messages.json")
            if os.path.exists(messages_path):
                with open(messages_path, encoding="utf-8") as f:
                    messages = json.load(f)
                if key in messages:
                    return messages[key]["message"]
    return name


def get_description(ext_dir, lang="en"):
    """Get description for the given language."""
    if lang == "en":
        en_path = os.path.join(ext_dir, "DESCRIPTION.en.md")
        if os.path.exists(en_path):
            with open(en_path, encoding="utf-8") as f:
                return f.read().strip()
    else:
        zh_path = os.path.join(ext_dir, "DESCRIPTION.md")
        if os.path.exists(zh_path):
            with open(zh_path, encoding="utf-8") as f:
                return f.read().strip()
    # Fallback to DESCRIPTION.md
    fallback = os.path.join(ext_dir, "DESCRIPTION.md")
    if os.path.exists(fallback):
        with open(fallback, encoding="utf-8") as f:
            return f.read().strip()
    return None


def make_badge(dir_name, color, label="Download"):
    badge_label = dir_name.replace("-", "--")
    download_url = f"{BASE_DOWNLOAD_URL}/{dir_name}.zip"
    badge_img = (
        f"https://img.shields.io/badge/{label}-{badge_label}.zip-{color}"
        f"?style=for-the-badge&logo=googlechrome"
    )
    return f"[![{label} {dir_name}]({badge_img})]({download_url})"


def list_files(ext_dir):
    return sorted(
        f for f in os.listdir(ext_dir)
        if not f.startswith(".") and os.path.isfile(os.path.join(ext_dir, f))
    )


def generate_readme(extensions, lang="en"):
    L = LABELS[lang]
    badge_text = L["badge_label"]

    lines = [
        LANG_TOGGLE,
        "",
        f"# {L['title']}",
        "",
        L["subtitle"],
        "",
        L["auto_note"],
        "",
        "---",
        "",
        f"## {L['quick_download']}",
        "",
        f"| # | {L['table_ext']} | {L['version']} | {L['table_download']} |",
        "|---|---------|------|------|",
    ]

    for i, ext in enumerate(extensions):
        dir_name = ext["dir"]
        ext_name = resolve_name(ext["manifest"], dir_name, lang)
        color = BADGE_COLORS[i % len(BADGE_COLORS)]
        badge = make_badge(dir_name, color, badge_text)
        anchor = f"ext-{dir_name}"
        ver = ext["manifest"].get("version", "")
        lines.append(f"| {i + 1} | [{ext_name}](#{anchor}) | `{ver}` | {badge} |")

    lines += ["", "---", "", f"## {L['ext_list']}", ""]

    for i, ext in enumerate(extensions):
        dir_name = ext["dir"]
        ext_name = resolve_name(ext["manifest"], dir_name, lang)
        color = BADGE_COLORS[i % len(BADGE_COLORS)]
        anchor = f"ext-{dir_name}"

        lines.append(f'<a id="{anchor}"></a>')
        lines.append("")
        lines.append(f"### {i + 1}. {ext_name}")
        lines.append("")
        lines.append(f"**{L['folder']}** `{dir_name}/`")
        lines.append("")
        ver = ext["manifest"].get("version")
        if ver:
            lines.append(f"**{L['version']}:** `{ver}`")
            lines.append("")

        detail = get_description(dir_name, lang)
        if not detail:
            detail = ext["manifest"].get("description", "")
        if detail:
            lines.append(detail)
            lines.append("")

        lines.append(f"**{L['download_btn']}**")
        lines.append("")
        lines.append(make_badge(dir_name, color, badge_text))
        lines.append("")

        lines.append(f"**{L['install']}**")
        for j, step in enumerate(L["install_steps"]):
            lines.append(f"{j + 1}. {step.format(dir=dir_name)}")
        lines += ["", "---", ""]

    # Project structure
    lines += [f"## {L['project_structure']}", "", "```", "stan-chrome-extensions/"]
    for j, ext in enumerate(extensions):
        dir_name = ext["dir"]
        files = list_files(dir_name)
        is_last_ext = j == len(extensions) - 1
        ext_prefix = "\u2514\u2500\u2500" if is_last_ext else "\u251C\u2500\u2500"
        lines.append(f"{ext_prefix} {dir_name}/")
        for k, f in enumerate(files):
            is_last_file = k == len(files) - 1
            indent = "    " if is_last_ext else "\u2502   "
            file_prefix = "\u2514\u2500\u2500" if is_last_file else "\u251C\u2500\u2500"
            lines.append(f"{indent}{file_prefix} {f}")
    lines += [
        "```",
        "",
        f"## {L['add_new']}",
        "",
        L["add_new_desc"],
        "",
        f"## {L['license']}",
        "",
        "MIT",
        "",
    ]

    return "\n".join(lines)


if __name__ == "__main__":
    # Always run from repo root
    repo_root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    os.chdir(repo_root)

    extensions = find_extensions()
    if not extensions:
        print("No extensions found!", file=sys.stderr)
        sys.exit(1)

    # Generate English README (default)
    readme_en = generate_readme(extensions, lang="en")
    with open("README.md", "w", encoding="utf-8") as f:
        f.write(readme_en)

    # Generate Chinese README
    readme_zh = generate_readme(extensions, lang="zh_TW")
    with open("README.zh-TW.md", "w", encoding="utf-8") as f:
        f.write(readme_zh)

    names = [e["dir"] for e in extensions]
    print(f"Generated README.md + README.zh-TW.md \u2014 {len(extensions)} extension(s): {names}")
